/**
 * Pithros Centralized Design System Tokens
 * 
 * Strict architectural tokens for colors, spacing, radii, typography,
 * shadows, motion timing, and breakpoints.
 */

export const DESIGN_SYSTEM = {
  colors: {
    sanctuary: {
      canvas: '#111820',
      canvasSubtle: '#182337',
      surface: '#182337',
      surfaceElevated: '#202C40',
      surfaceHover: '#283750',
      textPrimary: '#F8F5EE',
      textWarm: '#D9D2C6',
      textSecondary: '#D9D2C6',
      textMuted: '#9EA3AA',
      textDim: '#737982',
      accent: '#B99452',
      accentSoft: 'rgba(185, 148, 82, 0.15)',
      accentHover: '#D1B477',
      border: '#202C40',
      borderSubtle: '#182337',
      borderStrong: '#2D3D56',
      indigo: '#23324A',
      deepIndigo: '#182337',
      brass: '#B99452',
      lightBrass: '#D1B477',
      rose: '#A66B76',
      gold: '#B99452',
      success: '#4C8A6A',
      danger: '#C75B63',
      overlay: 'rgba(0, 0, 0, 0.75)',
    },
    archive: {
      canvas: '#F3EEE4',
      canvasSubtle: '#EBE5DA',
      surface: '#FCFAF5',
      surfaceElevated: '#E5DED2',
      surfaceHover: '#ECE4D8',
      card: '#FFFFFF',
      textPrimary: '#26262A',
      textHeadline: '#20242A',
      textWarm: '#554F48',
      textSecondary: '#554F48',
      textMuted: '#7D766D',
      textDim: '#7D766D',
      accent: '#23324A',
      accentSoft: 'rgba(35, 50, 74, 0.08)',
      accentHover: '#182337',
      border: '#E5DED2',
      borderSubtle: '#EDE7DD',
      borderStrong: '#D5CDC0',
      indigo: '#23324A',
      deepIndigo: '#182337',
      brass: '#B99452',
      lightBrass: '#D1B477',
      rose: '#A66B76',
      gold: '#B99452',
      success: '#397A5E',
      danger: '#B85B63',
      overlay: 'rgba(23, 25, 28, 0.45)',
    },
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
    '2xl': '32px',
    '3xl': '48px',
    '4xl': '64px',
  },
  radii: {
    none: '0px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '20px',
    '2xl': '24px',
    full: '9999px',
  },
  typography: {
    display: "'Noto Serif', 'Noto Serif Devanagari', 'Noto Serif Tamil', 'Noto Serif Telugu', 'Noto Serif Kannada', 'Noto Serif Malayalam', 'Noto Serif Bengali', 'Noto Serif Gujarati', 'Noto Serif Gurmukhi', Georgia, serif",
    serif: "'Noto Serif', 'Noto Serif Devanagari', 'Noto Serif Tamil', 'Noto Serif Telugu', 'Noto Serif Kannada', 'Noto Serif Malayalam', 'Noto Serif Bengali', 'Noto Serif Gujarati', 'Noto Serif Gurmukhi', Georgia, serif",
    sans: "'Noto Sans', 'Noto Sans Devanagari', 'Noto Sans Tamil', 'Noto Sans Telugu', 'Noto Sans Kannada', 'Noto Sans Malayalam', 'Noto Sans Bengali', 'Noto Sans Gujarati', 'Noto Sans Gurmukhi', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    monogram: "'Noto Serif', 'Noto Serif Devanagari', Georgia, serif",
  },
  motion: {
    micro: {
      min: 150,
      max: 220,
      standard: 180,
    },
    standard: {
      min: 250,
      max: 400,
      standard: 320,
    },
    emotional: {
      min: 500,
      max: 900,
      standard: 650,
    },
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
} as const;

export type PithrosColorPalette = typeof DESIGN_SYSTEM.colors.sanctuary;
