"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 10:56:42.491446

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memorials",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("preferred_name", sa.String(length=200), nullable=True),
        sa.Column("birth_date", sa.String(length=32), nullable=False),
        sa.Column("death_date", sa.String(length=32), nullable=False),
        sa.Column("birth_place", sa.String(length=200), nullable=False),
        sa.Column("resting_place", sa.String(length=200), nullable=True),
        sa.Column("short_epitaph", sa.Text(), nullable=False),
        sa.Column("portrait_url", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("privacy", sa.String(length=32), nullable=False),
        sa.Column("publication_state", sa.String(length=32), nullable=False),
        sa.Column("verification_state", sa.String(length=32), nullable=False),
        sa.Column("verification_badge_type", sa.String(length=64), nullable=True),
        sa.Column("theme", sa.String(length=32), nullable=False),
        sa.Column("completeness_percent", sa.Integer(), nullable=False),
        sa.Column("search_index_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "privacy IN ('private', 'family', 'unlisted', 'public')",
            name=op.f("ck_memorials_privacy_valid"),
        ),
        sa.CheckConstraint(
            "publication_state IN ('draft', 'published', 'archived')",
            name=op.f("ck_memorials_publication_state_valid"),
        ),
        sa.CheckConstraint(
            "theme IN ('classic', 'garden', 'horizon', 'candlelight', 'heritage')",
            name=op.f("ck_memorials_theme_valid"),
        ),
        sa.CheckConstraint(
            "verification_state IN ('draft', 'submitted', 'verification_pending', 'verification_review', 'approved', 'needs_more_information', 'rejected', 'appeal')",
            name=op.f("ck_memorials_verification_state_valid"),
        ),
        sa.CheckConstraint(
            "completeness_percent >= 0 AND completeness_percent <= 100",
            name=op.f("ck_memorials_completeness_percent_range"),
        ),
        sa.CheckConstraint("slug = lower(slug)", name=op.f("ck_memorials_slug_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memorials")),
    )
    op.create_index(
        "ix_memorials_public_discovery",
        "memorials",
        ["publication_state", "privacy", "search_index_enabled"],
        unique=False,
    )
    op.create_index(op.f("ix_memorials_slug"), "memorials", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("admin_subrole", sa.String(length=32), nullable=True),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "admin_subrole IS NULL OR admin_subrole IN ('super_admin', 'admin', 'verification_reviewer', 'moderator', 'provider_manager', 'support_agent', 'finance')",
            name=op.f("ck_users_admin_subrole_valid"),
        ),
        sa.CheckConstraint(
            "role IN ('visitor', 'family_steward', 'family_contributor', 'partner', 'admin')",
            name=op.f("ck_users_role_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'pending_verification')",
            name=op.f("ck_users_status_valid"),
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=200), nullable=False),
        sa.Column("actor_role", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_masked", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "result IN ('success', 'denied', 'flagged')", name=op.f("ck_audit_logs_result_valid")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_id", "created_at"], unique=False
    )
    op.create_index("ix_audit_logs_entity", "audit_logs", ["entity", "entity_id"], unique=False)
    op.create_table(
        "digital_legacy_links",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('youtube', 'facebook', 'instagram', 'linkedin', 'website', 'other')",
            name=op.f("ck_digital_legacy_links_platform_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_digital_legacy_links_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digital_legacy_links")),
    )
    op.create_index(
        op.f("ix_digital_legacy_links_memorial_id"),
        "digital_legacy_links",
        ["memorial_id"],
        unique=False,
    )
    op.create_table(
        "memorial_contributors",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("invited_email", sa.String(length=320), nullable=True),
        sa.Column("invited_by_id", sa.UUID(), nullable=True),
        sa.Column("invitation_token_hash", sa.String(length=128), nullable=True),
        sa.Column("invitation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("relationship_label", sa.String(length=120), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('steward', 'biographer', 'photo_archivist', 'memory_contributor', 'guest_reviewer', 'viewer')",
            name=op.f("ck_memorial_contributors_role_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'revoked')",
            name=op.f("ck_memorial_contributors_status_valid"),
        ),
        sa.CheckConstraint(
            "user_id IS NOT NULL OR invited_email IS NOT NULL",
            name=op.f("ck_memorial_contributors_user_or_invited_email_present"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
            name=op.f("fk_memorial_contributors_invited_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_memorial_contributors_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memorial_contributors_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memorial_contributors")),
    )
    op.create_index(
        op.f("ix_memorial_contributors_invitation_token_hash"),
        "memorial_contributors",
        ["invitation_token_hash"],
        unique=False,
    )
    op.create_index(
        "ix_memorial_contributors_invited_email",
        "memorial_contributors",
        ["invited_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memorial_contributors_memorial_id"),
        "memorial_contributors",
        ["memorial_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memorial_contributors_user_id"), "memorial_contributors", ["user_id"], unique=False
    )
    op.create_table(
        "memorial_media",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("privacy", sa.String(length=32), nullable=False),
        sa.Column("storage_tier", sa.String(length=32), nullable=False),
        sa.Column("storage_bucket", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("thumbnail_key", sa.String(length=512), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("year", sa.String(length=16), nullable=True),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('photo', 'video', 'voice', 'document')",
            name=op.f("ck_memorial_media_kind_valid"),
        ),
        sa.CheckConstraint(
            "privacy IN ('private', 'family', 'unlisted', 'public')",
            name=op.f("ck_memorial_media_privacy_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'rejected')",
            name=op.f("ck_memorial_media_status_valid"),
        ),
        sa.CheckConstraint(
            "storage_tier IN ('public', 'private', 'sensitive')",
            name=op.f("ck_memorial_media_storage_tier_valid"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_memorial_media_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_memorial_media_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_memorial_media_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memorial_media")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_memorial_media_storage_key")),
    )
    op.create_index(
        op.f("ix_memorial_media_memorial_id"), "memorial_media", ["memorial_id"], unique=False
    )
    op.create_index(
        "ix_memorial_media_memorial_status",
        "memorial_media",
        ["memorial_id", "status"],
        unique=False,
    )
    op.create_table(
        "memorial_permissions",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("permission", sa.String(length=64), nullable=False),
        sa.Column("granted_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "permission IN ('view', 'edit_details', 'edit_story', 'manage_timeline', 'manage_media', 'manage_contributors', 'manage_tributes', 'manage_privacy', 'change_theme', 'submit_verification', 'publish', 'archive', 'export_archive', 'transfer_stewardship', 'delete')",
            name=op.f("ck_memorial_permissions_permission_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["users.id"],
            name=op.f("fk_memorial_permissions_granted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_memorial_permissions_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memorial_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memorial_permissions")),
        sa.UniqueConstraint(
            "memorial_id", "user_id", "permission", name="memorial_user_permission"
        ),
    )
    op.create_index(
        "ix_memorial_permissions_user", "memorial_permissions", ["user_id"], unique=False
    )
    op.create_table(
        "memorial_stewards",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_memorial_stewards_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_memorial_stewards_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memorial_stewards")),
        sa.UniqueConstraint("memorial_id", "user_id", name="memorial_user"),
    )
    op.create_index(
        "uq_memorial_stewards_one_primary_per_memorial",
        "memorial_stewards",
        ["memorial_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "offerings",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("offering_type", sa.String(length=32), nullable=False),
        sa.Column("sender_name", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("sender_user_id", sa.UUID(), nullable=True),
        sa.Column("submitted_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "offering_type IN ('dove', 'flower', 'hands', 'light', 'star', 'heart', 'honor', 'memory', 'prayer')",
            name=op.f("ck_offerings_offering_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_offerings_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
            name=op.f("fk_offerings_sender_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offerings")),
    )
    op.create_index(op.f("ix_offerings_memorial_id"), "offerings", ["memorial_id"], unique=False)
    op.create_index(
        "ix_offerings_memorial_type", "offerings", ["memorial_id", "offering_type"], unique=False
    )
    op.create_table(
        "stories",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("early_life", sa.Text(), nullable=True),
        sa.Column("passions_and_values", sa.Text(), nullable=True),
        sa.Column("enduring_legacy", sa.Text(), nullable=True),
        sa.Column("favorite_quotes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_stories_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stories")),
        sa.UniqueConstraint("memorial_id", name=op.f("uq_stories_memorial_id")),
    )
    op.create_table(
        "timeline_events",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.String(length=16), nullable=False),
        sa.Column("date_str", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IS NULL OR category IN ('birth', 'milestone', 'family', 'career', 'memory', 'passing')",
            name=op.f("ck_timeline_events_category_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_timeline_events_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    op.create_index(
        op.f("ix_timeline_events_memorial_id"), "timeline_events", ["memorial_id"], unique=False
    )
    op.create_table(
        "tributes",
        sa.Column("memorial_id", sa.UUID(), nullable=False),
        sa.Column("author_name", sa.String(length=200), nullable=False),
        sa.Column("author_email", sa.String(length=320), nullable=True),
        sa.Column("relationship", sa.String(length=120), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("submitted_by_id", sa.UUID(), nullable=True),
        sa.Column("moderated_by_id", sa.UUID(), nullable=True),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("moderation_reason", sa.Text(), nullable=True),
        sa.Column("submitted_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending_moderation', 'approved', 'rejected', 'hidden')",
            name=op.f("ck_tributes_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["memorial_id"],
            ["memorials.id"],
            name=op.f("fk_tributes_memorial_id_memorials"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["moderated_by_id"],
            ["users.id"],
            name=op.f("fk_tributes_moderated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_tributes_submitted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tributes")),
    )
    op.create_index(op.f("ix_tributes_memorial_id"), "tributes", ["memorial_id"], unique=False)
    op.create_index(
        "ix_tributes_memorial_status", "tributes", ["memorial_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tributes_memorial_status", table_name="tributes")
    op.drop_index(op.f("ix_tributes_memorial_id"), table_name="tributes")
    op.drop_table("tributes")
    op.drop_index(op.f("ix_timeline_events_memorial_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_table("stories")
    op.drop_index("ix_offerings_memorial_type", table_name="offerings")
    op.drop_index(op.f("ix_offerings_memorial_id"), table_name="offerings")
    op.drop_table("offerings")
    op.drop_index(
        "uq_memorial_stewards_one_primary_per_memorial",
        table_name="memorial_stewards",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_table("memorial_stewards")
    op.drop_index("ix_memorial_permissions_user", table_name="memorial_permissions")
    op.drop_table("memorial_permissions")
    op.drop_index("ix_memorial_media_memorial_status", table_name="memorial_media")
    op.drop_index(op.f("ix_memorial_media_memorial_id"), table_name="memorial_media")
    op.drop_table("memorial_media")
    op.drop_index(op.f("ix_memorial_contributors_user_id"), table_name="memorial_contributors")
    op.drop_index(op.f("ix_memorial_contributors_memorial_id"), table_name="memorial_contributors")
    op.drop_index("ix_memorial_contributors_invited_email", table_name="memorial_contributors")
    op.drop_index(
        op.f("ix_memorial_contributors_invitation_token_hash"), table_name="memorial_contributors"
    )
    op.drop_table("memorial_contributors")
    op.drop_index(op.f("ix_digital_legacy_links_memorial_id"), table_name="digital_legacy_links")
    op.drop_table("digital_legacy_links")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_memorials_slug"), table_name="memorials")
    op.drop_index("ix_memorials_public_discovery", table_name="memorials")
    op.drop_table("memorials")
    # ### end Alembic commands ###
