"""concurrency, idempotency, audit detail, indexes

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 17:17:35.611224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name=op.f('ck_idempotency_keys_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('key', 'subject', name='key_subject')
    )
    op.create_index('ix_idempotency_keys_expires_at', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('task_failures',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('error_class', sa.String(length=120), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_failures'))
    )
    op.create_index('ix_task_failures_task_name_created', 'task_failures', ['task_name', 'created_at'], unique=False)
    op.create_index('ix_task_failures_unresolved', 'task_failures', ['resolved_at'], unique=False)
    op.add_column('audit_logs', sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_created', 'audit_logs', ['entity', 'created_at'], unique=False)
    op.create_index('ix_memorial_stewards_user_id', 'memorial_stewards', ['user_id'], unique=False)
    op.add_column('memorials', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.create_index('ix_offerings_memorial_created', 'offerings', ['memorial_id', 'created_at'], unique=False)
    op.create_index('ix_tributes_status', 'tributes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tributes_status', table_name='tributes')
    op.drop_index('ix_offerings_memorial_created', table_name='offerings')
    op.drop_column('memorials', 'version')
    op.drop_index('ix_memorial_stewards_user_id', table_name='memorial_stewards')
    op.drop_index('ix_audit_logs_entity_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_index('ix_task_failures_unresolved', table_name='task_failures')
    op.drop_index('ix_task_failures_task_name_created', table_name='task_failures')
    op.drop_table('task_failures')
    op.drop_index('ix_idempotency_keys_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
