"""verification lifecycle

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 22:37:34.603713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_submissions',
    sa.Column('memorial_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('automated_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('draft', 'submitted', 'verification_pending', 'verification_review', 'approved', 'needs_more_information', 'rejected', 'appeal')", name=op.f('ck_verification_submissions_state_valid')),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], name=op.f('fk_verification_submissions_memorial_id_memorials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_verification_submissions_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_verification_submissions_submitted_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_submissions'))
    )
    op.create_index('ix_verification_submissions_memorial', 'verification_submissions', ['memorial_id', 'created_at'], unique=False)
    op.create_index('ix_verification_submissions_state', 'verification_submissions', ['state'], unique=False)
    op.create_table('verification_decisions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('previous_state', sa.String(length=32), nullable=False),
    sa.Column('new_state', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_label', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("decision IN ('submitted', 'appealed', 'approved', 'rejected', 'needs_more_information')", name=op.f('ck_verification_decisions_decision_valid')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_verification_decisions_reviewer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['verification_submissions.id'], name=op.f('fk_verification_decisions_submission_id_verification_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_decisions'))
    )
    op.create_index('ix_verification_decisions_submission', 'verification_decisions', ['submission_id', 'created_at'], unique=False)
    op.create_table('verification_evidence',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("document_type IN ('death_certificate', 'obituary', 'funeral_notice', 'identity_proof', 'relationship_proof', 'other')", name=op.f('ck_verification_evidence_document_type_valid')),
    sa.ForeignKeyConstraint(['media_id'], ['memorial_media.id'], name=op.f('fk_verification_evidence_media_id_memorial_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['verification_submissions.id'], name=op.f('fk_verification_evidence_submission_id_verification_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_verification_evidence_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_evidence'))
    )
    op.create_index('ix_verification_evidence_submission', 'verification_evidence', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_evidence_submission', table_name='verification_evidence')
    op.drop_table('verification_evidence')
    op.drop_index('ix_verification_decisions_submission', table_name='verification_decisions')
    op.drop_table('verification_decisions')
    op.drop_index('ix_verification_submissions_state', table_name='verification_submissions')
    op.drop_index('ix_verification_submissions_memorial', table_name='verification_submissions')
    op.drop_table('verification_submissions')
    # ### end Alembic commands ###
