"""add_billing_subscriptions_and_entitlements

Revision ID: be676895f24f
Revises: 0003
Create Date: 2026-09-30 10:59:37.125532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be676895f24f'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code IN ('MEMORIAL_CARE', 'FAMILY_ARCHIVE', 'ADDITIONAL_MEMORIAL')", name=op.f('ck_plans_plan_code_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.create_index(op.f('ix_plans_product_type'), 'plans', ['product_type'], unique=False)
    op.create_table('webhook_events',
    sa.Column('gateway', sa.String(length=32), server_default=sa.text("'cashfree'"), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('processing_status', sa.String(length=32), server_default=sa.text("'received'"), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("processing_status IN ('received', 'processed', 'failed', 'ignored')", name=op.f('ck_webhook_events_webhook_processing_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_table('billing_accounts',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('billing_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), server_default=sa.text("'IN'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('tax_profile_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_billing_accounts_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_accounts'))
    )
    op.create_index(op.f('ix_billing_accounts_owner_user_id'), 'billing_accounts', ['owner_user_id'], unique=True)
    op.create_table('plan_prices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('billing_interval', sa.String(length=32), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('savings_copy', sa.String(length=255), nullable=True),
    sa.Column('monthly_equivalent_minor', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_interval IN ('monthly', 'half_yearly', 'annual')", name=op.f('ck_plan_prices_billing_interval_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_plan_prices_amount_positive')),
    sa.CheckConstraint('interval_count > 0', name=op.f('ck_plan_prices_interval_count_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_prices_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_prices'))
    )
    op.create_index(op.f('ix_plan_prices_plan_id'), 'plan_prices', ['plan_id'], unique=False)
    op.create_table('sponsorship_links',
    sa.Column('memorial_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('plan_price_id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_by_billing_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'redeemed', 'expired', 'revoked')", name=op.f('ck_sponsorship_links_sponsorship_status_valid')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sponsorship_links_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], name=op.f('fk_sponsorship_links_memorial_id_memorials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_price_id'], ['plan_prices.id'], name=op.f('fk_sponsorship_links_plan_price_id_plan_prices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['redeemed_by_billing_account_id'], ['billing_accounts.id'], name=op.f('fk_sponsorship_links_redeemed_by_billing_account_id_billing_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsorship_links'))
    )
    op.create_index(op.f('ix_sponsorship_links_memorial_id'), 'sponsorship_links', ['memorial_id'], unique=False)
    op.create_index(op.f('ix_sponsorship_links_token'), 'sponsorship_links', ['token'], unique=True)
    op.create_table('subscriptions',
    sa.Column('billing_account_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('gateway', sa.String(length=32), server_default=sa.text("'cashfree'"), nullable=False),
    sa.Column('gateway_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('gateway_schedule_id', sa.String(length=128), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('grace_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'past_due', 'grace', 'expired_read_only', 'cancelled', 'terminated', 'paused', 'payment_processing', 'retrying')", name=op.f('ck_subscriptions_subscription_status_valid')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_subscriptions_billing_account_id_billing_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['price_id'], ['plan_prices.id'], name=op.f('fk_subscriptions_price_id_plan_prices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_billing_account_id'), 'subscriptions', ['billing_account_id'], unique=False)
    op.create_index('ix_subscriptions_billing_status', 'subscriptions', ['billing_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_gateway_subscription_id'), 'subscriptions', ['gateway_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_price_id'), 'subscriptions', ['price_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('memorial_entitlements',
    sa.Column('billing_account_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('memorial_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'assigned'"), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('assigned', 'released', 'reserved')", name=op.f('ck_memorial_entitlements_memorial_entitlement_status_valid')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_memorial_entitlements_billing_account_id_billing_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], name=op.f('fk_memorial_entitlements_memorial_id_memorials'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_memorial_entitlements_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memorial_entitlements')),
    sa.UniqueConstraint('subscription_id', 'slot_number', name='uq_subscription_slot_number')
    )
    op.create_index('ix_memorial_entitlement_active', 'memorial_entitlements', ['memorial_id', 'status'], unique=False)
    op.create_index(op.f('ix_memorial_entitlements_billing_account_id'), 'memorial_entitlements', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_memorial_entitlements_memorial_id'), 'memorial_entitlements', ['memorial_id'], unique=False)
    op.create_index(op.f('ix_memorial_entitlements_subscription_id'), 'memorial_entitlements', ['subscription_id'], unique=False)
    op.create_table('payments',
    sa.Column('billing_account_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('plan_price_id', sa.String(length=64), nullable=False),
    sa.Column('memorial_id', sa.UUID(), nullable=True),
    sa.Column('internal_order_id', sa.String(length=64), nullable=False),
    sa.Column('gateway', sa.String(length=32), server_default=sa.text("'cashfree'"), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=128), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method_type', sa.String(length=32), nullable=True),
    sa.Column('payment_method_masked', sa.String(length=64), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'success', 'failed', 'flagged', 'refunded', 'disputed')", name=op.f('ck_payments_payment_status_valid')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_payments_billing_account_id_billing_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memorial_id'], ['memorials.id'], name=op.f('fk_payments_memorial_id_memorials'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_price_id'], ['plan_prices.id'], name=op.f('fk_payments_plan_price_id_plan_prices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payments_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_billing_account_id'), 'payments', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_order_id'), 'payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_internal_order_id'), 'payments', ['internal_order_id'], unique=True)
    op.create_index(op.f('ix_payments_memorial_id'), 'payments', ['memorial_id'], unique=False)
    op.create_index(op.f('ix_payments_plan_price_id'), 'payments', ['plan_price_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('subscription_entitlements',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('max_memorials', sa.Integer(), nullable=False),
    sa.Column('max_photos', sa.Integer(), nullable=False),
    sa.Column('max_video_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_audio_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_documents', sa.Integer(), nullable=False),
    sa.Column('max_contributors', sa.Integer(), nullable=False),
    sa.Column('verification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('archive_export_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('anniversary_notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('legacy_links_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('premium_theme_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_subscription_entitlements_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_entitlements'))
    )
    op.create_index(op.f('ix_subscription_entitlements_subscription_id'), 'subscription_entitlements', ['subscription_id'], unique=True)
    op.create_table('invoices',
    sa.Column('billing_account_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('tax_minor', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'paid'"), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_object_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'issued', 'paid', 'void', 'uncollectible')", name=op.f('ck_invoices_invoice_status_valid')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_invoices_billing_account_id_billing_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_invoices_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_invoices_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_billing_account_id'), 'invoices', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_payment_id'), 'invoices', ['payment_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=128), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed')", name=op.f('ck_refunds_refund_status_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_refunds_approved_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_refunds_requested_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_gateway_refund_id'), 'refunds', ['gateway_refund_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_gateway_refund_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_billing_account_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscription_entitlements_subscription_id'), table_name='subscription_entitlements')
    op.drop_table('subscription_entitlements')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_price_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_memorial_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_internal_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_account_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_memorial_entitlements_subscription_id'), table_name='memorial_entitlements')
    op.drop_index(op.f('ix_memorial_entitlements_memorial_id'), table_name='memorial_entitlements')
    op.drop_index(op.f('ix_memorial_entitlements_billing_account_id'), table_name='memorial_entitlements')
    op.drop_index('ix_memorial_entitlement_active', table_name='memorial_entitlements')
    op.drop_table('memorial_entitlements')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_price_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_gateway_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_end'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_billing_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_billing_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sponsorship_links_token'), table_name='sponsorship_links')
    op.drop_index(op.f('ix_sponsorship_links_memorial_id'), table_name='sponsorship_links')
    op.drop_table('sponsorship_links')
    op.drop_index(op.f('ix_plan_prices_plan_id'), table_name='plan_prices')
    op.drop_table('plan_prices')
    op.drop_index(op.f('ix_billing_accounts_owner_user_id'), table_name='billing_accounts')
    op.drop_table('billing_accounts')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_plans_product_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
