"""Cloudflare R2 helpers: a preflight round-trip and DB-driven cleanup.

Object keys are generated by the application (`memorials/{id}/...`), so cleanup
is driven by the E2E database: only objects referenced by test rows are removed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import boto3
from botocore.config import Config

from . import database


@dataclass
class R2Client:
    client: Any
    public_bucket: str
    private_bucket: str
    sensitive_bucket: str

    def put(self, bucket: str, key: str, data: bytes, content_type: str) -> None:
        self.client.put_object(Bucket=bucket, Key=key, Body=data, ContentType=content_type)

    def get(self, bucket: str, key: str) -> bytes:
        return self.client.get_object(Bucket=bucket, Key=key)["Body"].read()

    def delete(self, bucket: str, key: str) -> None:
        self.client.delete_object(Bucket=bucket, Key=key)

    def exists(self, bucket: str, key: str) -> bool:
        try:
            self.client.head_object(Bucket=bucket, Key=key)
            return True
        except Exception:
            return False


def build_r2(env: dict[str, str]) -> R2Client:
    missing = [
        name
        for name in (
            "R2_ENDPOINT_URL",
            "R2_ACCESS_KEY_ID",
            "R2_SECRET_ACCESS_KEY",
            "R2_BUCKET_PUBLIC",
            "R2_BUCKET_PRIVATE",
            "R2_BUCKET_SENSITIVE",
        )
        if not env.get(name)
    ]
    if missing:
        raise RuntimeError(f"R2 configuration is incomplete: missing {', '.join(missing)}")

    client = boto3.client(
        "s3",
        endpoint_url=env["R2_ENDPOINT_URL"],
        aws_access_key_id=env["R2_ACCESS_KEY_ID"],
        aws_secret_access_key=env["R2_SECRET_ACCESS_KEY"],
        region_name=env.get("R2_REGION", "auto"),
        config=Config(
            signature_version="s3v4",
            connect_timeout=5,
            read_timeout=30,
            retries={"max_attempts": 3, "mode": "standard"},
        ),
    )
    return R2Client(
        client=client,
        public_bucket=env["R2_BUCKET_PUBLIC"],
        private_bucket=env["R2_BUCKET_PRIVATE"],
        sensitive_bucket=env["R2_BUCKET_SENSITIVE"],
    )


def preflight(r2: R2Client, run_id: str) -> str:
    """Prove real storage works before any journey depends on it."""
    key = f"e2e/{run_id}/healthcheck.txt"
    payload = f"pithros-e2e {run_id}".encode()
    r2.put(r2.private_bucket, key, payload, "text/plain")
    try:
        fetched = r2.get(r2.private_bucket, key)
    finally:
        r2.delete(r2.private_bucket, key)
    if fetched != payload:
        raise RuntimeError("R2 preflight round-trip returned different bytes")
    return key


def cleanup_objects(r2: R2Client) -> tuple[int, int]:
    """Delete storage objects referenced by the E2E database. Returns counts."""
    deleted = 0
    failed = 0
    known_buckets = {r2.public_bucket, r2.private_bucket, r2.sensitive_bucket}
    for bucket, key in database.media_objects():
        if bucket not in known_buckets:
            # Rows written by the local filesystem adapter — not R2 objects.
            continue
        try:
            r2.delete(bucket, key)
            deleted += 1
        except Exception:
            failed += 1
    return deleted, failed
